export const ENV_CONFIG = {
  PASSWORD_SECRET: process.env.NEXT_PUBLIC_PASSWORD_SECRET as string,
  ACCESS_TOKEN_SECRET: process.env.NEXT_PUBLIC_ACCESS_TOKEN_SECRET as string,
  REFRESH_TOKEN_SECRET: process.env.NEXT_PUBLIC_REFRESH_TOKEN_SECRET as string,
  FORGOT_PASSWORD_TOKEN_SECRET: process.env
    .NEXT_PUBLIC_FORGOT_PASSWORD_TOKEN_SECRET as string,
  ACCESS_TOKEN_EXPIRES_IN: process.env
    .NEXT_PUBLIC_ACCESS_TOKEN_EXPIRES_IN as string,
  REFRESH_TOKEN_EXPIRES_IN: process.env
    .NEXT_PUBLIC_REFRESH_TOKEN_EXPIRES_IN as string,
  FORGOT_PASSWORD_TOKEN_EXPIRES_IN: process.env
    .NEXT_PUBLIC_FORGOT_PASSWORD_TOKEN_EXPIRES_IN as string,
} as const;
